server:
  port: 9001
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    username: /leyou
    password: leyou
    host: 127.0.0.1

jiwell:
  fcm:
    accessKeyId: LTAIc259TULYzaS7
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v
    signName: 乐优商城
    verifyCodeTemplate: SMS_148614415
