server:
  port: 10081
spring:
  application:
    name: mail-service
  rabbitmq:
    host: 10.140.0.4
    username: /ji-well
    password: ji-well
    virtual-host: /ji-well
    freemarker:
      cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    password: vtviuhrskuakilsj
    properties:
       mail:
        smtp:
          auth: true
          starttls:
             enable: true
             required: true
    username: sharebard@gmail.com
eureka:
  client:
    service-url:
      defaultZone: http://10.140.0.11:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 10.140.0.11
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
mail:
  from: ${spring.mail.username}
  to: w.sirius@gmail.com

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#logging:
#  file: mail-service.log #添加开启admin的日志监控
