server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /ji-well
    username: /ji-well
    password: ji-well
    host: 127.0.0.1

jiwell:
  sms:
    accessKeyId: LTAIc259TULYzaS7
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v
    signName: 乐优商城
    verifyCodeTemplate: SMS_148614415

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#logging:
#  file: sms-service.log #添加开启admin的日志监控